#!/bin/bash

source "$BASHLIB/libbash"
source "$BASHLIB/bashtask"

setup() {
    Announce "Doing setup!"
    mkdir -p "$SampleDir"
}

run() {
    Announce "Running task!"
    runIntro="\
Make a file inside $SampleDir/ and tell me what it's called!

To submit your response:
$ submit <file_name>
"
    Speak "$runIntro"
    RunTask
}

# This function returns 0 on success and 1 otherwise.
check_submission() {
    submission=$1

    respFile=$SampleDir/$submission
    if [ -f "$respFile" ]; then
        Announce "Good job!" BOLD BLUE
        Speak "$ExitMsg"
        return 0
    fi
    Announce "Error: file $respFile does not exist or is not a file" BOLD RED
    checkReminder="\
Remember, you want to create a file in $SampleDir/ and submit the file name"
    Speak "$checkReminder"
    return 1
}

# cleanup() is called whenever anything else fails, and once at the very end
cleanup() {
    Announce "Doing cleanup!"
    rm -rf "$SampleDir"
}

### Begin Main Script ###

set -e

arg=$1

SampleDir="/tmp/sampleBash"

TaskMain
