#!/bin/bash

export SCAVENGERSOURCEDIR="$HOME/scavenger"
export SCAVENGERDATADIR="$HOME/.scavenger"
export SCAVENGERHUNTSETTINGS="$HOME/.hunt_settings"
export SCAVENGERTASKPATH="$HOME/scavenger/task"
export SCAVENGERSTORYPATH="$HOME/scavenger/story"

export BASHLIB="$SCAVENGERSOURCEDIR/lib"
export PYTHONPATH="$PYTHONPATH:$SCAVENGERSOURCEDIR/lib"
