#!/bin/bash

export SOURCEDIR="$HOME/scavenger"
export DATADIR="$HOME/.scavenger"
export HUNTSETTINGS="$HOME/.hunt_settings"

export BASHLIB="$SOURCEDIR/lib"
export PYTHONPATH="$PYTHONPATH:$SOURCEDIR/lib"
