#!/bin/bash

rootProvision() {
    yum install -y git
    mkdir -p /etc/scavenger
}

userProvision() {
    sudo ln -s ~/scavenger/scavenger /usr/local/bin/
    sudo ln -s ~/scavenger/environment /etc/scavenger/
    git clone https://github.com/ResComp/scavenger
    cat <<"EOF" >> ~/.bashrc
PS1="\${SCAVENGERHUNTINGPROMPT}[\u \w]\\$ "

if [ -f ~/.hunt_settings ]; then
    . ~/.hunt_settings
fi
EOF
}

arg=$1

if [ "$arg" = "root" ]; then
    rootProvision
elif [ "$arg" = "user" ]; then
    userProvision
fi
