#!/bin/bash

rootProvision() {
    yum install -y git
}

userProvision() {
    git clone https://github.com/ResComp/scavenger
    cat <<"EOF" >> ~/.bashrc
PS1="\${HuntingPrompt}[\u \w]\\$ "

if [ -f ~/.hunt_settings ]; then
    . ~/.hunt_settings
fi
EOF
}

arg=$1

if [ "$arg" = "root" ]; then
    rootProvision
elif [ "$arg" = "user" ]; then
    userProvision
fi
