#!/bin/bash

source "$BASHLIB/libbash"
source "$BASHLIB/bashTask"

setup() {
    Announce 0 "Doing setup!"
    mkdir -p "$SampleDir"
}

read -r -d '' runIntro <<"EOF"
Make a file inside %s/ and tell me what it's called!

To submit your response:
$ submit <file_name>
EOF

run() {
    Announce 0 "Running task!"
    printf "${runIntro}\n\n" "$SampleDir"
    RunTask
}

read -r -d '' checkReminder <<"EOF"
Remember, you want to create a file in %s/ and submit the file name
EOF

# This function returns 0 on success and 1 otherwise.
check_submission() {
    submission=$1

    respFile=$SampleDir/$submission
    if [ -f "$respFile" ]; then
        Announce 1 "Good job!"
        echo "$ExitMsg"
        return 0
    fi
    Announce 2 "Error: file $respFile does not exist or is not a file"
    printf "${checkReminder}\n" "$SampleDir"
    return 1
}

# cleanup() is called whenever anything else fails, and once at the very end
cleanup() {
    Announce 0 "Doing cleanup!"
    rm -rf "$SampleDir"
}

### Begin Main Script ###

set -e

arg=$1

SampleDir="/tmp/sampleBash"

TaskMain "$arg"
