#!/bin/bash

source "$HOME/scavenger/lib/libbash"

setup() {
    Announce 0 "Doing setup!"
    mkdir -p "$workDir"
}

read -r -d '' runIntro << EOF
Make a file inside %s and tell me what it's called!

To submit your response:
$ submit <file_name>
EOF

run() {
    Announce 0 "Running task!"
    printf "${runIntro}\n\n" "$workDir"

    # Run submission checker in the background
    checker &
    checkerPID=$!
    # Create a pid file to track the process so it can be cleaned up
    CreatePIDFile "$pidFile" "$checkerPID"

    # Run a shell for the user to play with
    $SHELL
}

read -r -d '' checkReminder << EOF
Remember, you want to create a file in %s and submit the file name
EOF

# This is a loop that reads from the submission pipe
checker() {
    while true; do
        if read submission < $SubmitPipe; then
            respFile=$workDir/$submission
            if [ -f "$respFile" ]; then
                Announce 1 "Good job!"
                echo "$ExitMsg"
                break
            fi
            Announce 2 "Error: file $respFile does not exist or is not a file"
            printf "${checkReminder}\n" "$workDir"
        fi
    done
}

# cleanup() is called whenever anything else fails, and once at the very end
cleanup() {
    Announce 0 "Doing cleanup!"
    rm -rf "$workDir"
    CleanupProcess "$pidFile"
}

### Begin Main Script ###

set -e
trap cleanup SIGHUP SIGINT SIGTERM

arg=$1

workDir="/tmp/sampleTask"
pidFile="/var/run/sampleTask.pid"

RunTask "$arg"
