#!/usr/bin/env python

import pystory

class DefaultStory(pystory.Story):
    """
    So what do we want to teach them about?
    - XXX READING THE LOGS
    - shell tools
    - dotfiles (config files in general)
    - where to find things (/etc vs /bin vs /usr ...etc.)
    - services
    - firewall (just let them know it exists)
    - selinux (just let them know it exists)
    - how-to write shell
    - XXX READING THE LOGS

    Ideas
    - process that spawns others that print to screen, have them use ps, tr, cut,
      and kill
    """
    def setup(self):
        pass

    def run(self):
        self.run_tasks(self.tasks)

    def cleanup(self):
        pass

if __name__ == "__main__":
    story = DefaultStory(["samplePython", "pathExplorer"])
    story.main()
