#!/bin/bash

source "$HOME/scavenger/lib/libbash"

ExitMsg='You may now exit out of this shell with the keys "ctrl+d" or the "exit" command'

# This takes as input the name of the pid file. Not the path.
#
# pid files are assumed to be in RunDir
# Here a pid file is one that contains only the pid of the process
CleanupProcess() {
    pidFileName=$1

    pidFile="$RunDir/$pidFileName"
    # Open the pid file only if it exists
    if [ -f "$pidFile" ]; then
        pid=$(cat $pidFile)
        # Kill the process only if it's still running
        if [ -e "/proc/$pid" ]; then
            kill "$pid"
        fi
        if [ -e "/proc/$pid" ]; then
            kill -9 "$pid"
        fi
        rm -f $pidFile
    fi
}

# This calls the functions setup(), run(), and cleanup() as appropriate
RunTask() {
    arg=$1

    if [ "$arg" = "setup" ]; then
        setup
    elif [ "$arg" = "run" ]; then
        run
    elif [ "$arg" = "cleanup" ]; then
        cleanup
    fi
}
