#!/bin/bash

PipeDir="/var/run/scavenger"
SubmitPipe="$PipeDir/submit"
ExitMsg='You can now exit out of this shell with the keys ctrl+d or the `exit` command'

Text() {
    setting="$1" # "0" = bold, "1" = blue, "2" = red
    message=$2

    normal=$(tput sgr0)
    different=$(tput bold)
    if [ "$setting" = "1" ]; then
        different="${different}$(tput setaf 4)"
    elif [ "$setting" = "2" ]; then
        different="${different}$(tput setaf 1)"
    elif [ "$setting" = "3" ]; then
        different=$normal
    fi

    echo -n -e "${different}${message}${normal}"
}

Announce() {
    Text "$1" "\n${2}\n\n"
}

# This takes in a pid file as a input where the only content of the file is
# the pid of the process
CleanupProcess() {
    pidFile=$1

    # Open the pid file only if it exists
    if [ -f "$pidFile" ]; then
        pid=$(cat $pidFile)
        # kill the process only if it's still running
        if [ -e "/proc/$pid" ]; then
            sudo kill -9 "$pid"
        fi
        sudo rm -f $pidFile
    fi
}
